### ISSUE TITLE
Boxes are displayed at the wrong position on IE11

### ISSUE THREAD

**Issue by wbadam** [vaadin/board#107]
Vaadin Framework 8.1.0.rc1
Vaadin Board 1.0.0.beta1

When creating a demo Vaadin (Java) application using the [Row Types example](https://demo.vaadin.com/vaadin-board/#/row-types), the boxes' layout is wrong on IE11.

Both `vaadin-board` and `vaadin-board-precompiled` are a dependency.

The results are similar to the following pictures.
On IE:
![vaadinboard_ie11](https://user-images.githubusercontent.com/15823229/28212174-7e138632-68a0-11e7-95ed-a13823fab84d.png)

On FF:
![vaadinboard_firefox](https://user-images.githubusercontent.com/15823229/28212176-80cf2552-68a0-11e7-9a6b-72a456a8e946.png)

**Comment by DiegoCardoso** [comment]
Thanks, we will be looking into this issue.

**Comment by vlukashov** [comment]
Fixed in the PR #110. The fix will be included into the next beta release of Vaadin Board.

**Comment by vlukashov** [comment]
The fix is available in the version 1.0.0-beta2
