### ISSUE TITLE
User should be notified if they are missing the vaadin-board-precompiled dependency

### ISSUE THREAD

**Issue by johannesh2** [vaadin/board#98]
Currently it's possible to compile and run an application with having only the vaadin-board maven dependency. If you forget to add the precompiled module, you get only weird client-side exceptions and strange behavior in the app, but no clear message/warning why this might be happening. Some helpful guiding message at least in runtime would be appreciated.

**Comment by Peppe** [comment]
Great idea. Any thoughts on how this could be implemented?

The message itself could be a short sentence with a link to the instructions, instead of a full description in the error message. The link could for example point to a wiki entry in this GitHub repository.

**Comment by alvarezguille** [comment]
I think some client-side check for the Board or BoardRow definition should work.
I'd rather link to documentation, instead of adding docs to github wiki, just to keep a single source of truth.

**Comment by Peppe** [comment]
Yeah. Sounds reasonable. A FAQ kind of article with numbered headers?

**Comment by Artur-** [comment]
What if we make board-precompiled a dependency instead? Most people will want it for fw8
